# Generated by Django 5.1.3 on 2024-11-26 14:04

import Assesment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(upload_to=Assesment.models.document_upload_to),
        ),
    ]
